ci: pass passphrases for non-interactive use

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -38,6 +38,13 @@ jobs:
       DEVICE_NAME: "bluejay"
 
     steps:
+      - name: Check if `root` is true and `magisk-preinit-device` is set
+        run: |
+          if [ "${{ github.event.inputs.root }}" == "true" ] && [ -z "${{ github.event.inputs.magisk-preinit-device }}" ]; then
+            echo "Error: magisk-preinit-device is required when root is true."
+            exit 1
+          fi
+
       - name: Checkout code
         uses: actions/checkout@v4
         with:
@@ -71,8 +78,8 @@ jobs:
           GRAPHENEOS_VERSION: ${{ github.event.inputs.ota-version }}
           FORCE_UPDATE: ${{ github.event.inputs.force-ota-server-upload }}
           MAGISK_PREINTI: ${{ github.event.inputs.magisk-preinit-device }}
-          PASSPHRASE_AVB: ${{ secrets.AVB_PASSPHRASE }}
-          PASSPHRASE_OTA: ${{ secrets.OTA_PASSPHRASE }}
+          PASSPHRASE_AVB: ${{ secrets.PASSPHRASE_AVB }}
+          PASSPHRASE_OTA: ${{ secrets.PASSPHRASE_OTA }}
         run: |
           echo "DEVICE_NAME=${{ github.event.inputs.device-id || env.DEVICE_NAME }}" >> $GITHUB_ENV
           echo "Running release script"
