feat: read from `env` when `schedule` and abort if `DEVICE_NAME` not passed

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -62,29 +62,49 @@ jobs:
           # Allow for switching to github-pages branch
           fetch-depth: 0
       
+      - name: Read from `env.toml` if exist
+        if: ${{ github.event_name == 'schedule' }}
+        run: |
+          toml_file="env.toml"
+          if [ -f "$toml_file" ]; then
+            DEVICE_NAME=$(grep '^device_name =' "$toml_file" | sed -E 's/^device_name *= *"([^"]*)"/\1/')
+            UPDATE_CHANNEL=$(grep '^update_channel =' "$toml_file" | sed -E 's/^update_channel *= *"([^"]*)"/\1/')
+        
+            # Export the variables
+            echo -e "DEVICE_NAME=${DEVICE_NAME}" >> $GITHUB_ENV
+            echo -e "UPDATE_CHANNEL=${UPDATE_CHANNEL}" >> $GITHUB_ENV
+        
+            echo -e "DEVICE_NAME: $DEVICE_NAME"
+            echo -e "UPDATE_CHANNEL: $UPDATE_CHANNEL"
+          fi
+          
       - name: Check if a build exists already and verify assets
         shell: bash
         run: |
-          url="https://releases.grapheneos.org/${{ env.DEVICE_NAME }}-${{ github.event.inputs.update-channel || 'alpha' }}"
-          latest_grapheneos_version=$(curl -sL ${url} | sed 's/ .*//')
-          echo "REMOTE_GRAPHENEOS_VERSION=${latest_grapheneos_version}" >> $GITHUB_ENV
-      
+          if [[ -z "${DEVICE_NAME}" ]]; then
+            echo -e "::error::Missing required param \`DEVICE_NAME\`"
+            exit 1
+          fi
+          
+          source src/fetcher.sh && get_latest_version
+          echo -e "GRAPHENEOS_VERSION=${VERSION[GRAPHENEOS]}" >> $GITHUB_ENV
+          
           # Determine if the build is based on magisk or rootless
           build_flavor=$([[ ${{ github.event.inputs.root == 'true' }} == 'true' ]] && echo 'magisk' || echo 'rootless')
       
           # Check if the tag exists
-          if git show-ref --tags ${latest_grapheneos_version} --quiet; then
-            echo "Tag with GrapheneOS version ${latest_grapheneos_version} already exists. Looking for assets..."
+          if git show-ref --tags ${VERSION[GRAPHENEOS]} --quiet; then
+            echo -e "Tag with GrapheneOS version ${VERSION[GRAPHENEOS]} already exists. Looking for assets..."
             # Fetch the release information for the tag
-            repo_url="https://api.github.com/repos/${{ github.repository }}/releases/tags/${latest_grapheneos_version}"
-            release_info=$(curl -sL "$repo_url")
+            repo_url="https://api.github.com/repos/${{ github.repository }}/releases/tags/${VERSION[GRAPHENEOS]}"
+            release_info=$(curl -sL -H "Authorization: token ${{ secrets.PAT_TEST }}" "$repo_url")
             
             # Define required assets
             required_assets=(
-              "${{ env.DEVICE_NAME }}-${latest_grapheneos_version}-magisk-*.zip"
-              "${{ env.DEVICE_NAME }}-${latest_grapheneos_version}-magisk-*.zip.csig"
-              "${{ env.DEVICE_NAME }}-${latest_grapheneos_version}-rootless-*.zip"
-              "${{ env.DEVICE_NAME }}-${latest_grapheneos_version}-rootless-*.zip.csig"
+              "${{ env.DEVICE_NAME }}-${VERSION[GRAPHENEOS]}-magisk-*.zip"
+              "${{ env.DEVICE_NAME }}-${VERSION[GRAPHENEOS]}-magisk-*.zip.csig"
+              "${{ env.DEVICE_NAME }}-${VERSION[GRAPHENEOS]}-rootless-*.zip"
+              "${{ env.DEVICE_NAME }}-${VERSION[GRAPHENEOS]}-rootless-*.zip.csig"
             )
       
             existing_assets=$(echo "$release_info" | jq -r '.assets[].name')
